name: Keepalive

on:
  schedule:
    - cron: '0 0 1,15 * *'  # 毎月1日と15日
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore: keepalive [skip ci]" || echo "No changes"
          git push origin HEAD:${GITHUB_REF}
